### ISSUE TITLE
update to latest coc.nvim update for custom completion key

### ISSUE THREAD

**Issue by mohamad-supangat** [albingroen/quick.nvim#12]
https://github.com/neoclide/coc.nvim/blob/1d9a26af85e33a7197d9ed2979a966e6e1b100bb/doc/coc.txt#L345

**Comment by visionm45** [comment]
these three lines ( 8, 9 & 10) in the coc-config.lua need to be modified in order to work with the update 


old


vim.api.nvim_set_keymap("i", "<TAB>", "pumvisible() ? '<C-n>' : '<TAB>'", {noremap = true, silent = true, expr = true})

vim.api.nvim_set_keymap("i", "<S-TAB>", "pumvisible() ? '<C-p>' : '<C-h>'", {noremap = true, expr = true})

vim.api.nvim_set_keymap("i", "<CR>", "pumvisible() ? coc#_select_confirm() : '<C-G>u<CR><C-R>=coc#on_enter()<CR>'", {silent = true, expr = true, noremap = true})


new 


vim.api.nvim_set_keymap("i", "<TAB>", "coc#pum#visible() ? coc#pum#next(1) : '<TAB>'", {noremap = true, silent = true, expr = true})

vim.api.nvim_set_keymap("i", "<S-TAB>", "coc#pum#visible() ? coc#pum#prev(1) : '<C-h>'", {noremap = true, expr = true})

vim.api.nvim_set_keymap("i", "<CR>", "coc#pum#visible() ? coc#_select_confirm() : '<C-G>u<CR><C-R>=coc#on_enter()<CR>'", {silent = true, expr = true, noremap = true})

**Comment by mohamad-supangat** [comment]
> these three lines ( 8, 9 & 10) in the coc-config.lua need to be modified in order to work with the update
> 
> old
> 
> vim.api.nvim_set_keymap("i", "", "pumvisible() ? '' : ''", {noremap = true, silent = true, expr = true})
> 
> vim.api.nvim_set_keymap("i", "", "pumvisible() ? '' : ''", {noremap = true, expr = true})
> 
> vim.api.nvim_set_keymap("i", "", "pumvisible() ? coc#_select_confirm() : 'u=coc#on_enter()'", {silent = true, expr = true, noremap = true})
> 
> new
> 
> vim.api.nvim_set_keymap("i", "", "coc#pum#visible() ? coc#pum#next(1) : ''", {noremap = true, silent = true, expr = true})
> 
> vim.api.nvim_set_keymap("i", "", "coc#pum#visible() ? coc#pum#prev(1) : ''", {noremap = true, expr = true})
> 
> vim.api.nvim_set_keymap("i", "", "coc#pum#visible() ? coc#_select_confirm() : 'u=coc#on_enter()'", {silent = true, expr = true, noremap = true})

tanks for

> these three lines ( 8, 9 & 10) in the coc-config.lua need to be modified in order to work with the update
> 
> old
> 
> vim.api.nvim_set_keymap("i", "", "pumvisible() ? '' : ''", {noremap = true, silent = true, expr = true})
> 
> vim.api.nvim_set_keymap("i", "", "pumvisible() ? '' : ''", {noremap = true, expr = true})
> 
> vim.api.nvim_set_keymap("i", "", "pumvisible() ? coc#_select_confirm() : 'u=coc#on_enter()'", {silent = true, expr = true, noremap = true})
> 
> new
> 
> vim.api.nvim_set_keymap("i", "", "coc#pum#visible() ? coc#pum#next(1) : ''", {noremap = true, silent = true, expr = true})
> 
> vim.api.nvim_set_keymap("i", "", "coc#pum#visible() ? coc#pum#prev(1) : ''", {noremap = true, expr = true})
> 
> vim.api.nvim_set_keymap("i", "", "coc#pum#visible() ? coc#_select_confirm() : 'u=coc#on_enter()'", {silent = true, expr = true, noremap = true})

tanks
